package com.smartclinic.web;
import com.smartclinic.model.*; import com.smartclinic.repository.*; import com.smartclinic.service.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api") public class ApiController {
 private final DoctorRepository doctors; private final PatientRepository patients; private final PrescriptionRepository prescriptions; private final DoctorService doctorService; private final AppointmentService appointmentService; private final TokenService tokens;
 public ApiController(DoctorRepository d,PatientRepository p,PrescriptionRepository pr,DoctorService ds,AppointmentService as,TokenService t){doctors=d;patients=p;prescriptions=pr;doctorService=ds;appointmentService=as;tokens=t;}
 private void auth(String h){if(h==null)throw new IllegalArgumentException("Требуется токен");tokens.validate(h);}
 @PostMapping("/login") public ResponseEntity<?> login(@RequestBody Map<String,String> b){String role=b.get("role"),email=b.get("email"),pass=b.get("password"); boolean ok="admin".equals(role)&&"admin@clinic.local".equals(email)&&"admin123".equals(pass)||"doctor".equals(role)&&doctors.findByEmail(email).filter(x->x.getPassword().equals(pass)).isPresent()||"patient".equals(role)&&patients.findByEmail(email).filter(x->x.getPassword().equals(pass)).isPresent(); return ok?ResponseEntity.ok(Map.of("token",tokens.generateToken(email,role),"role",role)):ResponseEntity.status(401).body(Map.of("error","Неверный логин или пароль"));}
 @GetMapping("/doctors") public List<Doctor> doctors(@RequestParam(required=false) String specialty,@RequestParam(required=false) String name){return name!=null?doctors.findByNameContainingIgnoreCase(name):doctorService.available(specialty);}
 @PostMapping("/doctors") public Doctor addDoctor(@RequestHeader("Authorization") String h,@RequestBody Doctor d){auth(h);return doctors.save(d);}
 @GetMapping("/doctors/{id}/appointments") public List<Appointment> doctorAppointments(@RequestHeader("Authorization") String h,@PathVariable Long id,@RequestParam String date){auth(h);return appointmentService.forDoctorOn(id,LocalDate.parse(date));}
 @PostMapping("/appointments") public Appointment book(@RequestHeader("Authorization") String h,@RequestBody Map<String,String> b){auth(h);return appointmentService.book(Long.valueOf(b.get("doctorId")),Long.valueOf(b.get("patientId")),LocalDateTime.parse(b.get("appointmentTime")));}
 @GetMapping("/patients/{id}/appointments") public List<Appointment> patientAppointments(@RequestHeader("Authorization") String h,@PathVariable Long id){auth(h);return appointmentService.forPatient(id);}
 @PostMapping("/prescriptions") public ResponseEntity<?> prescription(@RequestHeader("Authorization") String h,@RequestBody Map<String,String> b){auth(h); try{Prescription p=new Prescription();p.setDoctor(doctors.findById(Long.valueOf(b.get("doctorId"))).orElseThrow());p.setPatient(patients.findById(Long.valueOf(b.get("patientId"))).orElseThrow());p.setMedication(b.get("medication"));return ResponseEntity.ok(prescriptions.save(p));}catch(Exception e){return ResponseEntity.badRequest().body(Map.of("error",e.getMessage()));}}
}
